### ISSUE TITLE
On delete cascade

### ISSUE THREAD

**Issue by leetbox** [ackerdev/objection-softdelete#7]
Hi I want to know. Does it supports on delete cascade?

**Comment by capaj** [comment]
no it does not. This is out of scope for this small library. If you want to have "soft delete" and SQL cascading, you need to implement it yourself.

**Comment by ackerdev** [comment]
It does not, sorry.

I have no personal plans to implement this, as I'm not actively working in JavaScript right now, so I'm going to close this as "won't fix", but I'd be more than happy to review a PR that implements this and publish a new version for it!
