### ISSUE TITLE
related query del() patches everything, doesn't filter deleted ones by default

### ISSUE THREAD

**Issue by capaj** [ackerdev/objection-softdelete#8]
When I delete like this:
```ts
this.$relatedQuery('myRelation').del()
```

it patches all the items, so if I want to only patch those that are not deleted yet, I have to write it like this::
```ts
this.$relatedQuery('myRelation').del().where({ deleted_at: null })
```
which is super non intuitive.

**Comment by ackerdev** [comment]
Fixed in c2399f9, available in 3.0.0 release
